steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/greenmobility-damage-report/my-next-app:latest', '.' ]
images:
  - 'gcr.io/greenmobility-damage-report/my-next-app:latest'
